# Site settings
title: 二笨笨的博客
email: heruicross@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  二笨笨写字的地方
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: red3
github_username:  red3

# Build settings
markdown: kramdown
